events {}

http {

    # Aumentar límite de subida desde 1MB
    client_max_body_size 15M;

    # Xa que se vean bien las imágenes (mime types)
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        # El servidor Nginx escuchará en el puerto 80
        listen 80;

        # Definimos el nombre del servidor
        server_name 673bd45f-8f51-4f9e-bfdf-ad161612c2a6.pc.birt.eus;

        #Subida de ficheros
        location /uploads/ {
            root /var/www;
            autoindex off; # Por seguridad, para que no listen los ficheros
        }

        #Para que certbot pueda poner ahí el challenge
        location /.well-known/acme-challenge/ {
            # Sirve los archivos desde el volumen que comparte Nginx con Certbot
            # Esta es la ruta DENTRO del contenedor de Nginx
            root /var/www/certbot;
        }

        # Todas las peticiones (/) se redirigirán
        location / {
            # 'backend' es el nombre del servicio de Spring Boot en docker-compose.yaml
            # '8080' es el puerto donde corre Spring Boot DENTRO de Docker
            proxy_pass http://backend:8080;

            # Cabeceras importantes para el reenvío
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

}
